apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  MYSQL_DATABASE: accounts
  MYSQL_ROOT_PASSWORD: SomeComplexPassword

## To inject into the pod

apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db
    project: infinity
spec:
  containers:
  - name: mysql-container
    image: mysql:5.7
    # Using the below method HOW MANY EVER variables are there in the db-config, will be exported to the container.
    envFrom:
      - configMapRef:
          name: db-config
    # Using the below method if we want to use ONLY A SPECIFIC VARIABLE from the configMap
    env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: db-config 
            key: DB_HOST