---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system: authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXF4cmd3cVZjQm5RR1lCTmp1NWdmanovU21ncW9VNVpFVnpCMDg3dWZHZ3dkCkQrYlVqNVlQdFAvVHd2UmxJNThvWTVkU3p4Nk1lUkY3M20xQmcreHZCc3FPVjh1eVBoeVZvQndnNmp1amJJWUsKckd4TmtiaHlCWGN5a1YvMzlKVlJ2bW5IOWFncjU2Q2twZ3czVi93QjROZUJGZlZGcFVKcndHZ0lQbmFTQ2xORApabFo0bTRRcXE3TEEzQnBQUy9yaHF2OXdodjdmRFkxcUNRbU1DZFREZTJGU2lmUThOUVRwQWNQbWlPVndqTnE1CmliREpnenBnSHNsU2ZnOWkyaUlpay8yVkZTMERtVGNkaDRqNDRWd2RQMVA4UHlBSTBpNU9LTFZqa3NYYlR2VkIKTndXR0xMYXgyZVFweWw5aGJpOHdVUk1GYWozVEtESURXMER6VVZGNXVRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRVBWYUgvajYrUnBTY2Q2ZnBrU1NncE9WYXBLTy95dzNLQ0VmS1ZxZnZqN2R4TVNxRFRZCkE2MTNnRnBiWS96bkpoUFhKczdoMWcrK09rYWx5YXc4V3M2NXY5RDUvQklLUUNCbTI0NW94aFg0QkdYcWx1SU8KSUtSYTV5cnVTUXJBWU9KUzlVZU5hWGZQR1RGcXJHeGFQcmQ5VkV2NERBYU8yL2Z3ZlNLOGhlREVBbjAyU2RkUwp1Vk13QkwxQ0Zua1ZhazV6WVJwY3liLzlBZEM4K0FSQTNFbFpUbkhLd1Z2RG5yWjRQcjVoNTNzVWI2OHpEUysxCkZuajVpZGRtSVBhVTd1NWRTVWpYNWJERFVxL2hjaTFVUkNJbm9IMlB6WmNXRXRqZGJCZkZtR2pGM0Z5Q3hZcVoKU2t3UXZzT1E3WnlzdWs0di8wYUNMMCt2QU5sT1dOMUNNUmM9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
