apiVersion: v1
kind: Pod
metadata:
  # name and label are siblings
  # This name is the name of the Pod
  name: app-pod
  labels:
    # app and tier are children of Labels
    # This app represents the app to which the pod and container belongs  
    app: app
    # This represents the tier.
    tier: frontend
spec:
  containers:
    # The name below represents the name of the container that will be running within the pod 
    - name: nginx-container
      ## Image Name. If using repos other than Docker, mention full path
      image: nginx 
   
