apiVersion: v1
kind: Pod
# Metadata has data about the pod.Dictionaries
metadata:
  name: webapp-pod
  labels:
    app: frontend
    project: infinity
spec:
  containers: # Dictionary
  - name: httpd-container
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: http-port
        containerPort: 80
