apiVersion: v1
kind: Pods
metadata:
  name: web-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep","1000"]
    securityContext: 
      runAsUser: 1000
      capabilites:
        add: ["MAC_ADMIN"]
