apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  # Deploy the pod within a specific namespace
  namespace: dev
  labels:
    app: myapp
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
