apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demo-command
spec:
  containers:
  - name: command-demo
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME","KUBERNETES_PORT"]
    env:
    - name: MESSAGE
      value: "Hello World"
    command: ["/bin/echo"]
    args: ["Hello World"] 
  restartPolicy: OnFailure
