## This set of Defintion files, will create a new Persistent Disk on the GCP, assign it to the PVC and in turn will be assigned to the pod.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: google-storage
  resources:
    requests: 
      storage: 500Mi
 
 ## Above PVC Definition File will reference to the below storageClass file

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: google-storage
provisioner: kubernetes.io/gce-pd

## Associated Pod Definition File

apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh", "-c"]
    args: [shuf -i 0-100 -n 1 >> /opt/path]
    volumeMounts:
      - mountPath: /opt
        name: data-volume
    volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: myclaim
