apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myapp-repl
  labels:
    app: myapp
    type: front-end
spec: 
  # The below line specifies the total numbe rof pods to be running at any given time.
  replicas: 3 
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-controller
        image: nginx
 selector:
    matchlabels:
      ## Note: The below label matches with the label info from the spec.template.metadata.labels.type.
      type: front-end
