apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-webapp
  labels: 
    app: Appl
    function: Front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Appl
  template:
    metadata:
      labels:
        app: Appl
        function: Front-end
    spec:
      containers:
        - name: simple-webapp
          image: simple-webapp
          
