apiVersion: apps/v1                 # Note: The apiVersion for replicaset is apps/v1
kind: ReplicaSet
metadata: 
  name: myapp-repl
  labels:
    app: myapp
    type: front-end
spec: 
  replicas: 3                        # The below line specifies the total numbe rof pods to be running at any given time.
  selector:                          # The replicaset requires the selector section.
    matchLabels:                     # Note: The below label matches with the label info from the spec.template.metadata.labels.type.
      type: front-end
  template:
    metadata:
      labels:
        name: myapp-pod
        type: front-end
    spec:
      containers:
      - name: nginx-controller
        image: nginx
 
