# run command echo -n 'mysql' | base64 - To create an encoded value 
# then add the values to the respective key
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: bXlzcWw=
  DB_USER: cm9vdA==
  DB_Password: cGFzc3dvcmQ=