apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  # Cluster IP is the default service, even if none was mentioned, it is taken as a default value.
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
  selector:
  # Values for the selector are taken from the pod definition file.
    app: myapp
    name: back-end

## Associated Pod Definition file for reference
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: back-end
spec:
  containers:
  - name: nginx-container
    image: nginx