apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec: 
  ports:
    ## Port stands for Front-end Port
  - port: 80
    ## TargetPort stands for Backend Port
    targetPort: vproapp-port
    protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer
